--
-- PostgreSQL database dump
--

\restrict qeEL3Ay79UfOJAlimlRmDylHPDUiDa1SLkBiq3UqgHL4KSpoVHlgE4IVsbjCYRl

-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.11

-- Started on 2026-09-26 00:45:45

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16437)
-- Name: activite; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.activite (
    id bigint NOT NULL,
    description character varying(255),
    photo character varying(255),
    type character varying(255)
);


ALTER TABLE public.activite OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16436)
-- Name: activite_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.activite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16445)
-- Name: actualite; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.actualite (
    id bigint NOT NULL,
    contenu character varying(255),
    date_publication timestamp(6) without time zone,
    photo character varying(255),
    titre character varying(255),
    type character varying(255)
);


ALTER TABLE public.actualite OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16444)
-- Name: actualite_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.actualite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actualite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16453)
-- Name: demande_proforma; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.demande_proforma (
    id bigint NOT NULL,
    adresse character varying(255),
    commentaire character varying(255),
    date_creation timestamp(6) without time zone,
    email character varying(255),
    nom character varying(255),
    prenom character varying(255),
    quantite integer,
    societe character varying(255),
    statut character varying(255),
    telephone character varying(255),
    vehicule_id bigint
);


ALTER TABLE public.demande_proforma OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16452)
-- Name: demande_proforma_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.demande_proforma ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.demande_proforma_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16461)
-- Name: utilisateur; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.utilisateur (
    id bigint NOT NULL,
    email character varying(255),
    mot_de_passe character varying(255),
    nom character varying(255),
    prenom character varying(255),
    role character varying(255)
);


ALTER TABLE public.utilisateur OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16460)
-- Name: utilisateur_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.utilisateur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.utilisateur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16469)
-- Name: vehicule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vehicule (
    id bigint NOT NULL,
    annee integer,
    caracteristiques_techniques character varying(255),
    couleur character varying(255),
    description character varying(255),
    disponibilite boolean,
    gamme character varying(255),
    image character varying(255),
    modele character varying(255),
    motorisation character varying(255),
    options character varying(255),
    prix double precision,
    transmission character varying(255),
    version character varying(255)
);


ALTER TABLE public.vehicule OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16468)
-- Name: vehicule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vehicule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4874 (class 0 OID 16437)
-- Dependencies: 218
-- Data for Name: activite; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.activite (id, description, photo, type) FROM stdin;
1	Découvrez nos véhicules neufs et bénéficiez de l'accompagnement de notre équipe commerciale.	agence.jpg	Showroom
2	Entretien, diagnostic électronique, mécanique, carrosserie et peinture.	agence.jpg	Atelier
3	Pièces d'origine, accessoires, pneumatiques, huiles et batteries.	agence.jpg	Magasin
\.


--
-- TOC entry 4876 (class 0 OID 16445)
-- Dependencies: 220
-- Data for Name: actualite; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.actualite (id, contenu, date_publication, photo, titre, type) FROM stdin;
1	Explorez les nouveaux modèles disponibles chez E3S Sfax Silver Star.	2026-09-16 16:35:16.732581	\N	Découvrez notre nouvelle gamme Mercedes-Benz	Nouveauté
2	Notre atelier accompagne votre Mercedes-Benz pour l'entretien et la maintenance.	2026-09-16 16:35:16.738413	\N	Service après-vente E3S	Service
\.


--
-- TOC entry 4878 (class 0 OID 16453)
-- Dependencies: 222
-- Data for Name: demande_proforma; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.demande_proforma (id, adresse, commentaire, date_creation, email, nom, prenom, quantite, societe, statut, telephone, vehicule_id) FROM stdin;
1	REGUEB	hgkjbhj	2026-09-17 15:56:34.821737	eyaabdelli@gmail.com	abdelli	eya	1	sfax silver star	En attente	50850256	1
2	REGUEB		2026-09-18 10:49:23.403214	eyaabdelli@gmail.com	abdelli	eya	1	sfax silver star	En attente	50850256	4
3	REGUEB		2026-09-24 23:01:58.925434	eyaabdelli@gmail.com	abdelli	eya	1	sfax silver star	En attente	50850256	1
\.


--
-- TOC entry 4880 (class 0 OID 16461)
-- Dependencies: 224
-- Data for Name: utilisateur; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.utilisateur (id, email, mot_de_passe, nom, prenom, role) FROM stdin;
1	admin@e3s-mercedes.tn	$2a$10$Oj5bwBN2SKNTjlBSJgdk4uTZovxbTdJSRuERCNyxd6tt5uQ6HPq/O	Administrateur	E3S	ADMIN
2	eyaabdelli@gmail.com	$2a$10$ra.dxmqybEwHamYtA0v/D.mNnd6o6h9uLVtChkM5MIJzbDGmpHt/a	Administrateur	E3S	ADMIN
\.


--
-- TOC entry 4882 (class 0 OID 16469)
-- Dependencies: 226
-- Data for Name: vehicule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.vehicule (id, annee, caracteristiques_techniques, couleur, description, disponibilite, gamme, image, modele, motorisation, options, prix, transmission, version) FROM stdin;
1	2026	Moteur 1.3L, boîte automatique, 5 places.	gris charbon	Berline compacte premium et polyvalente.	t	Berline compacte	classe-a.jpg	Classe A	Essence 1.3L	Caméra de recul; Écran central; Aide au stationnement	149900	Automatique	200 Progressive
2	2026	Moteur 1.3L, boîte automatique, 5 places.	bleu marine	Espace, confort et polyvalence au quotidien.	t	Monospace compact	classe-b.jpg	Classe B	Essence 1.3L	Écran central; Climatisation; Régulateur de vitesse	165900	Automatique	180 Style
6	2026	Diesel 2.0L, boîte automatique, 5 places.	Rouge	SUV premium associant confort et robustesse.	t	SUV	glc.jpg	GLC	Diesel 2.0L	4MATIC; Pack AMG; MBUX	259900	Automatique	220d AMG Line
4	2026	Diesel 2.0L, boîte automatique, 5 places.	gris	Confort et technologie pour les longs trajets.	t	Berline premium	classe-e.jpg	Classe E	Diesel 2.0L	MBUX; Navigation; Assistance conduite	239900	Automatique	220d Avantgarde
5	2026	Essence 1.3L, boîte automatique, 5 places.	Gris souris	SUV compact, dynamique et polyvalent.	t	SUV compact	gla.jpg	GLA	Essence 1.3L	Caméra; MBUX; Jantes alliage	179900	Automatique	200 Progressive
3	2025	Diesel 2.0L, boîte automatique, propulsion.	Noir	Élégance et sportivité avec finition AMG Line.	t	Berline	classe-c.jpg	Classe C	Diesel 2.0L	Pack AMG Line; LED; Aide au stationnement	189900	Automatique	220d AMG Line
7	2026	Diesel 2.0L, boîte automatique, 5 à 7 places.	blanc	Grand SUV premium pour un confort exceptionnel.	f	Grand SUV	gle.jpg	GLE	Diesel 2.0L	4MATIC; Toit panoramique; Assistance conduite	349900	Automatique	300d AMG Line
\.


--
-- TOC entry 4888 (class 0 OID 0)
-- Dependencies: 217
-- Name: activite_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.activite_id_seq', 3, true);


--
-- TOC entry 4889 (class 0 OID 0)
-- Dependencies: 219
-- Name: actualite_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.actualite_id_seq', 2, true);


--
-- TOC entry 4890 (class 0 OID 0)
-- Dependencies: 221
-- Name: demande_proforma_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.demande_proforma_id_seq', 3, true);


--
-- TOC entry 4891 (class 0 OID 0)
-- Dependencies: 223
-- Name: utilisateur_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.utilisateur_id_seq', 4, true);


--
-- TOC entry 4892 (class 0 OID 0)
-- Dependencies: 225
-- Name: vehicule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.vehicule_id_seq', 7, true);


--
-- TOC entry 4716 (class 2606 OID 16443)
-- Name: activite activite_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activite
    ADD CONSTRAINT activite_pkey PRIMARY KEY (id);


--
-- TOC entry 4718 (class 2606 OID 16451)
-- Name: actualite actualite_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actualite
    ADD CONSTRAINT actualite_pkey PRIMARY KEY (id);


--
-- TOC entry 4720 (class 2606 OID 16459)
-- Name: demande_proforma demande_proforma_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.demande_proforma
    ADD CONSTRAINT demande_proforma_pkey PRIMARY KEY (id);


--
-- TOC entry 4722 (class 2606 OID 16477)
-- Name: utilisateur ukrma38wvnqfaf66vvmi57c71lo; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilisateur
    ADD CONSTRAINT ukrma38wvnqfaf66vvmi57c71lo UNIQUE (email);


--
-- TOC entry 4724 (class 2606 OID 16467)
-- Name: utilisateur utilisateur_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilisateur
    ADD CONSTRAINT utilisateur_pkey PRIMARY KEY (id);


--
-- TOC entry 4726 (class 2606 OID 16475)
-- Name: vehicule vehicule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicule
    ADD CONSTRAINT vehicule_pkey PRIMARY KEY (id);


--
-- TOC entry 4727 (class 2606 OID 16478)
-- Name: demande_proforma fkssjb4shb3ttpumbio4w0hfcla; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.demande_proforma
    ADD CONSTRAINT fkssjb4shb3ttpumbio4w0hfcla FOREIGN KEY (vehicule_id) REFERENCES public.vehicule(id);


-- Completed on 2026-09-26 00:45:46

--
-- PostgreSQL database dump complete
--

\unrestrict qeEL3Ay79UfOJAlimlRmDylHPDUiDa1SLkBiq3UqgHL4KSpoVHlgE4IVsbjCYRl

